name: "devrelease:docker"

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - release-*
    paths:
      - utils/docker/**
      - browsers.json
      - .github/workflows/trigger_canary_docker.yml
      - src/nativeDeps.ts

jobs:
  trigger-docker-canary:
    name: "Trigger Docker build"
    runs-on: ubuntu-20.04
    if: github.repository == 'microsoft/playwright'
    steps:
    - run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.REPOSITORY_DISPATCH_PERSONAL_ACCESS_TOKEN }}" \
          --data "{\"event_type\": \"build_docker_canary\", \"client_payload\": {\"ref\": \"${{ github.sha }}\"}}" \
          https://api.github.com/repos/microsoft/playwright-internal/dispatches
